-- Create risk_assessments table for storing agent output
-- GeoPoint stored as JSONB {lat, lng} - no PostGIS required

CREATE TABLE IF NOT EXISTS risk_assessments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id UUID NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    risk_category TEXT NOT NULL CHECK (risk_category IN ('healthy', 'monitoring', 'at-risk', 'critical', 'disrupted')),
    severity_score INT NOT NULL CHECK (severity_score >= 1 AND severity_score <= 10),
    confidence FLOAT NOT NULL CHECK (confidence >= 0.0 AND confidence <= 1.0),
    reasoning JSONB NOT NULL,
    affected_entities JSONB DEFAULT '[]'::jsonb,
    alternatives JSONB DEFAULT '{"suppliers": [], "routes": []}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for fast event lookups
CREATE INDEX idx_risk_assessments_event_id ON risk_assessments(event_id);

-- Index for risk category filtering
CREATE INDEX idx_risk_assessments_category ON risk_assessments(risk_category);

-- Index for severity filtering
CREATE INDEX idx_risk_assessments_severity ON risk_assessments(severity_score);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_risk_assessments_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-update updated_at
CREATE TRIGGER trigger_update_risk_assessments_updated_at
    BEFORE UPDATE ON risk_assessments
    FOR EACH ROW
    EXECUTE FUNCTION update_risk_assessments_updated_at();

-- Comments
COMMENT ON TABLE risk_assessments IS 'Risk assessments generated by the Risk Agent for supply chain entities';
COMMENT ON COLUMN risk_assessments.event_id IS 'Reference to the event that triggered this assessment';
COMMENT ON COLUMN risk_assessments.risk_category IS 'Risk level: healthy, monitoring, at-risk, critical, disrupted';
COMMENT ON COLUMN risk_assessments.reasoning IS 'Structured reasoning: {summary, factors, event_ids}';
COMMENT ON COLUMN risk_assessments.affected_entities IS 'Array of affected nodes/connections with distance_km';
COMMENT ON COLUMN risk_assessments.alternatives IS 'Alternative suppliers or routes: {suppliers: [], routes: []}';

-- Enable Row Level Security
ALTER TABLE risk_assessments ENABLE ROW LEVEL SECURITY;

-- Policy to allow authenticated users to read
CREATE POLICY "Allow authenticated read" ON risk_assessments
    FOR SELECT TO authenticated USING (true);

-- Policy to allow service role full access
CREATE POLICY "Allow service role full access" ON risk_assessments
    FOR ALL TO service_role USING (true);
