import { create } from 'zustand';
import type {
  AppState,
  SupplyNode,
  SupplyRoute,
  RiskZone,
  AlternativeSupplier,
  TariffBarrier,
  Vessel,
  NewsItem,
  TimelineEvent,
} from '../types';

// Sample data - Comprehensive electronics supply chain
const sampleNodes: SupplyNode[] = [
  {
    id: 'tsmc',
    name: 'TSMC Fab 18',
    type: 'supplier',
    coordinates: [120.21, 22.99],
    country: 'Taiwan',
    countryCode: 'TW',
    riskScore: 78,
    metadata: {
      company: 'TSMC',
      products: ['5nm chips', '3nm chips'],
      capacity: 92,
      leadTime: 45,
      unitCost: 2.40,
    },
  },
  {
    id: 'shanghai',
    name: 'Shanghai Port',
    type: 'port',
    coordinates: [121.47, 31.23],
    country: 'China',
    countryCode: 'CN',
    riskScore: 45,
    metadata: {},
  },
  {
    id: 'shenzhen',
    name: 'Shenzhen Assembly',
    type: 'factory',
    coordinates: [114.06, 22.54],
    country: 'China',
    countryCode: 'CN',
    riskScore: 52,
    metadata: {
      company: 'Foxconn',
      products: ['iPhone', 'MacBook'],
      capacity: 85,
    },
  },
  {
    id: 'singapore',
    name: 'Singapore Hub',
    type: 'port',
    coordinates: [103.85, 1.29],
    country: 'Singapore',
    countryCode: 'SG',
    riskScore: 15,
    metadata: {},
  },
  {
    id: 'la',
    name: 'Los Angeles Port',
    type: 'port',
    coordinates: [-118.25, 33.75],
    country: 'USA',
    countryCode: 'US',
    riskScore: 12,
    metadata: {},
  },
  {
    id: 'rotterdam',
    name: 'Rotterdam Port',
    type: 'port',
    coordinates: [4.48, 51.92],
    country: 'Netherlands',
    countryCode: 'NL',
    riskScore: 8,
    metadata: {},
  },
  {
    id: 'austin',
    name: 'Austin Distribution Center',
    type: 'warehouse',
    coordinates: [-97.74, 30.27],
    country: 'USA',
    countryCode: 'US',
    riskScore: 8,
    metadata: {},
  },
  {
    id: 'munich',
    name: 'Munich Warehouse',
    type: 'warehouse',
    coordinates: [11.58, 48.14],
    country: 'Germany',
    countryCode: 'DE',
    riskScore: 10,
    metadata: {},
  },
];

const sampleRoutes: SupplyRoute[] = [
  {
    id: 'tsmc-shenzhen',
    name: 'TSMC to Shenzhen Assembly',
    sourceId: 'tsmc',
    destinationId: 'shenzhen',
    coordinates: [[120.21, 22.99], [114.06, 22.54]],
    transportMode: 'air',
    estimatedDays: 1,
    status: 'at-risk',
    riskScore: 72,
  },
  {
    id: 'shenzhen-shanghai',
    name: 'Shenzhen to Shanghai Port',
    sourceId: 'shenzhen',
    destinationId: 'shanghai',
    coordinates: [[114.06, 22.54], [121.47, 31.23]],
    transportMode: 'rail',
    estimatedDays: 2,
    status: 'healthy',
    riskScore: 35,
  },
  {
    id: 'shanghai-singapore',
    name: 'Shanghai to Singapore',
    sourceId: 'shanghai',
    destinationId: 'singapore',
    coordinates: [[121.47, 31.23], [103.85, 1.29]],
    transportMode: 'sea',
    estimatedDays: 5,
    status: 'healthy',
    riskScore: 22,
  },
  {
    id: 'shanghai-la',
    name: 'Shanghai to Los Angeles',
    sourceId: 'shanghai',
    destinationId: 'la',
    coordinates: [[121.47, 31.23], [-118.25, 33.75]],
    transportMode: 'sea',
    estimatedDays: 14,
    status: 'healthy',
    riskScore: 25,
  },
  {
    id: 'shanghai-rotterdam',
    name: 'Shanghai to Rotterdam',
    sourceId: 'shanghai',
    destinationId: 'rotterdam',
    coordinates: [[121.47, 31.23], [4.48, 51.92]],
    transportMode: 'sea',
    estimatedDays: 28,
    status: 'at-risk',
    riskScore: 65,
  },
  {
    id: 'la-austin',
    name: 'LA to Austin',
    sourceId: 'la',
    destinationId: 'austin',
    coordinates: [[-118.25, 33.75], [-97.74, 30.27]],
    transportMode: 'rail',
    estimatedDays: 3,
    status: 'healthy',
    riskScore: 10,
  },
  {
    id: 'rotterdam-munich',
    name: 'Rotterdam to Munich',
    sourceId: 'rotterdam',
    destinationId: 'munich',
    coordinates: [[4.48, 51.92], [11.58, 48.14]],
    transportMode: 'rail',
    estimatedDays: 2,
    status: 'healthy',
    riskScore: 12,
  },
];

const sampleRiskZones: RiskZone[] = [
  {
    id: 'taiwan-earthquake',
    name: 'Taiwan Seismic Activity',
    type: 'earthquake',
    coordinates: [120.5, 23.5],
    intensity: 0.85,
    radius: 200,
    description: '6.2 magnitude earthquake detected near Tainan',
  },
  {
    id: 'taiwan-political',
    name: 'Taiwan Strait Tensions',
    type: 'political',
    coordinates: [119, 24],
    intensity: 0.95,
    radius: 400,
    description: 'Military exercises announced, shipping delays expected',
  },
  {
    id: 'red-sea',
    name: 'Red Sea Conflict',
    type: 'war',
    coordinates: [42, 15],
    intensity: 1.0,
    radius: 500,
    description: 'Ongoing conflict disrupting major shipping lanes',
  },
  {
    id: 'suez-tariff',
    name: 'Suez Canal Zone',
    type: 'tariff',
    coordinates: [32.5, 30],
    intensity: 0.6,
    radius: 200,
    description: 'Increased transit fees affecting shipping costs',
  },
  {
    id: 'hurricane-gulf',
    name: 'Gulf of Mexico Storm',
    type: 'storm',
    coordinates: [-90, 25],
    intensity: 0.7,
    radius: 350,
    description: 'Tropical storm affecting Gulf shipping routes',
  },
  {
    id: 'south-china-political',
    name: 'South China Sea Tensions',
    type: 'political',
    coordinates: [115, 12],
    intensity: 0.75,
    radius: 450,
    description: 'Territorial disputes causing shipping uncertainties',
  },
];

const sampleAlternatives: AlternativeSupplier[] = [
  {
    id: 'samsung',
    name: 'Samsung Foundry',
    coordinates: [127.05, 37.07],
    country: 'South Korea',
    riskScore: 23,
    costDelta: 8,
    leadTimeDays: 52,
    capacity: 85,
    rank: 1,
  },
  {
    id: 'intel',
    name: 'Intel Foundry Services',
    coordinates: [-111.89, 33.31],
    country: 'USA',
    riskScore: 12,
    costDelta: 22,
    leadTimeDays: 38,
    capacity: 70,
    rank: 2,
  },
  {
    id: 'globalfoundries',
    name: 'GlobalFoundries Dresden',
    coordinates: [13.74, 51.05],
    country: 'Germany',
    riskScore: 18,
    costDelta: 15,
    leadTimeDays: 48,
    capacity: 78,
    rank: 3,
  },
];

const sampleTariffBarriers: TariffBarrier[] = [
  {
    id: 'us-china-chips',
    name: 'US-China Semiconductor Tariffs',
    sourceCountry: 'China',
    targetCountry: 'USA',
    sourceCoordinates: [116.4, 39.9],
    targetCoordinates: [-77.04, 38.9],
    tariffPercent: 25,
    products: ['semiconductors', 'electronics'],
    effectiveDate: new Date('2023-01-01'),
  },
  {
    id: 'eu-china-ev',
    name: 'EU-China EV Tariffs',
    sourceCountry: 'China',
    targetCountry: 'EU',
    sourceCoordinates: [116.4, 39.9],
    targetCoordinates: [4.35, 50.85],
    tariffPercent: 45,
    products: ['electric vehicles', 'batteries'],
    effectiveDate: new Date('2024-07-01'),
  },
];

const sampleVessels: Vessel[] = [
  {
    id: 'v1',
    mmsi: '123456789',
    name: 'COSCO Shanghai',
    coordinates: [125.5, 28.5],
    heading: 45,
    speed: 18,
    destination: 'Los Angeles',
    path: [[121.47, 31.23], [123.5, 30.0], [125.5, 28.5]],
    timestamps: [0, 1000, 2000],
  },
  {
    id: 'v2',
    mmsi: '987654321',
    name: 'Maersk Eindhoven',
    coordinates: [55, 12],
    heading: 280,
    speed: 16,
    destination: 'Rotterdam',
    path: [[103.85, 1.29], [80, 8], [55, 12]],
    timestamps: [0, 1500, 3000],
  },
  {
    id: 'v3',
    mmsi: '456789123',
    name: 'Ever Given II',
    coordinates: [34, 28],
    heading: 350,
    speed: 14,
    destination: 'Rotterdam',
    path: [[103.85, 1.29], [60, 15], [34, 28]],
    timestamps: [0, 2000, 4000],
  },
];

const sampleNews: NewsItem[] = [
  {
    id: '1',
    title: 'US announces 50% tariff increase on semiconductor imports from Taiwan',
    source: 'Reuters',
    timestamp: new Date(Date.now() - 2 * 60 * 1000),
    severity: 'critical',
    region: 'Asia-Pacific',
    impactScore: 95,
  },
  {
    id: '2',
    title: 'Military exercises announced in Taiwan Strait, shipping delays expected',
    source: 'GDELT',
    timestamp: new Date(Date.now() - 15 * 60 * 1000),
    severity: 'critical',
    region: 'Taiwan Strait',
    impactScore: 90,
  },
  {
    id: '3',
    title: '6.2 magnitude earthquake detected near Tainan Science Park',
    source: 'USGS',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000),
    severity: 'warning',
    region: 'Taiwan',
    impactScore: 75,
  },
  {
    id: '4',
    title: 'Red Sea shipping diversions add 10-14 days to Europe routes',
    source: 'Lloyd\'s List',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
    severity: 'critical',
    region: 'Middle East',
    impactScore: 85,
  },
  {
    id: '5',
    title: 'Samsung Foundry announces capacity expansion in South Korea',
    source: 'Nikkei',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
    severity: 'positive',
    region: 'South Korea',
    impactScore: 40,
  },
  {
    id: '6',
    title: 'Port of Los Angeles reports record throughput despite global disruptions',
    source: 'Port Authority',
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000),
    severity: 'info',
    region: 'North America',
    impactScore: 30,
  },
];

const sampleTimelineEvents: TimelineEvent[] = [
  {
    id: 'e1',
    timestamp: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    type: 'disaster',
    severity: 'critical',
    title: 'Taiwan Earthquake',
  },
  {
    id: 'e2',
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    type: 'policy',
    severity: 'warning',
    title: 'Tariff Announcement',
  },
  {
    id: 'e3',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    type: 'disaster',
    severity: 'critical',
    title: 'Military Exercises',
  },
];

export const useStore = create<AppState>((set) => ({
  // Initial state
  viewMode: 'live',
  selectedNodeId: null,
  selectedRouteId: null,
  showAlternatives: false,
  simulationActive: false,
  placementMode: false,

  nodes: sampleNodes,
  routes: sampleRoutes,
  riskZones: sampleRiskZones,
  alternatives: sampleAlternatives,
  tariffBarriers: sampleTariffBarriers,
  vessels: sampleVessels,
  news: sampleNews,
  timelineEvents: sampleTimelineEvents,
  chatMessages: [],
  simulatedRoutes: [],

  sidebarTab: 'intel',
  timelinePosition: 100,
  currentTime: 0,

  // Actions
  setViewMode: (mode) => set({ viewMode: mode }),

  selectNode: (id) => set({
    selectedNodeId: id,
    selectedRouteId: null,
    sidebarTab: id ? 'details' : 'intel',
    showAlternatives: id !== null,
  }),

  selectRoute: (id) => set({
    selectedRouteId: id,
    selectedNodeId: null,
    sidebarTab: id ? 'details' : 'intel',
    showAlternatives: id !== null,
  }),

  setShowAlternatives: (show) => set({ showAlternatives: show }),

  setSimulationActive: (active) => set({
    simulationActive: active,
    viewMode: active ? 'simulation' : 'live',
  }),

  setPlacementMode: (mode) => set({ placementMode: mode }),

  setSidebarTab: (tab) => set({ sidebarTab: tab }),

  setTimelinePosition: (pos) => set({
    timelinePosition: pos,
    viewMode: pos < 95 ? 'historical' : 'live',
  }),

  setCurrentTime: (time) => set({ currentTime: time }),

  addNode: (node) => set((state) => ({ nodes: [...state.nodes, node] })),

  addRoute: (route) => set((state) => ({ routes: [...state.routes, route] })),

  updateNodes: (nodes) => set({ nodes }),

  updateRoutes: (routes) => set({ routes }),

  updateRiskZones: (zones) => set({ riskZones: zones }),

  updateVessels: (vessels) => set({ vessels: vessels }),

  updateNews: (news) => set({ news }),

  addChatMessage: (message) => set((state) => ({
    chatMessages: [...state.chatMessages, message]
  })),

  setSimulatedRoutes: (routes) => set({ simulatedRoutes: routes }),
}));
